services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1

  api:
    build: .
    container_name: dataflow-api
    ports:
      - "8000:8000"
    depends_on:
      - localstack
    environment:
      # OpenAI (for RAG)
      - OPENAI_API_KEY=${OPENAI_API_KEY}

      # AWS creds for LocalStack
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1

      # LocalStack S3 endpoint
      - AWS_ENDPOINT_URL=http://localstack:4566
    volumes:
      # Mount FAISS index(not part of image)
      - ./rag/index:/app/rag/index
